version: '{build}'

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

os: Windows Server 2012

install:
  - cmd: choco install maven -y -f
  - cmd: refreshenv

build_script:
- mvn clean install test

artifacts:
  - path: '*.war'
  
deploy:
- release: Validation-Manager-$(appveyor_build_version)
- description: 'Release description'
- provider: GitHub
- auth_token:
  - secure: <your encrypted token> # your encrypted token from GitHub
- artifact: /.*\.war/              # upload all war packages to release assets
- draft: true
- prerelease: true
- on:
  - branch: master                 # release from master branch only
  - appveyor_repo_tag: true        # deploy on tag push only
