version: 0.4.{build}
skip_tags: true
max_jobs: 1
build_script:
- cmd: mvn clean install test
artifacts:
- path: '**/*.war'
  name: Validation Manager
deploy:
- provider: GitHub
  tag: Validation-Manager-$(appveyor_build_version)
  release: Validation-Manager-$(appveyor_build_version)
  auth_token:
    secure: Q+yCBAEnNqT5Hev/C+ulKi/kZzuiYvS283deJFMusBZxYEfGrSdubOZ9lwWVaRDu
  artifact: '**/*.war'
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: master
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true