/*Add user status*/
INSERT INTO "USER_STATUS" ("ID", "STATUS", "DESCRIPTION") VALUES (1, 'user.status.active', 'user.status.active.desc');
INSERT INTO "USER_STATUS" ("ID", "STATUS", "DESCRIPTION") VALUES (2, 'user.status.inactive', 'user.status.inactive.desc');
INSERT INTO "USER_STATUS" ("ID", "STATUS", "DESCRIPTION") VALUES (3, 'user.status.locked', 'user.status.locked.desc');
INSERT INTO "USER_STATUS" ("ID", "STATUS", "DESCRIPTION") VALUES (4, 'user.status.aged', 'user.status.aged.desc');
/*Add roles*/
INSERT INTO "ROLE" ("ID", "ROLE_NAME", "DESCRIPTION") VALUES (1, 'reserved1', 'reserver.desc');
INSERT INTO "ROLE" ("ID", "ROLE_NAME", "DESCRIPTION") VALUES (2, 'reserved2', 'reserved2.desc');
INSERT INTO "ROLE" ("ID", "ROLE_NAME", "DESCRIPTION") VALUES (3, 'none', 'none.desc');
INSERT INTO "ROLE" ("ID", "ROLE_NAME", "DESCRIPTION") VALUES (4, 'test.designer', 'test.designer.desc');
INSERT INTO "ROLE" ("ID", "ROLE_NAME", "DESCRIPTION") VALUES (5, 'guest', 'guest.desc');
INSERT INTO "ROLE" ("ID", "ROLE_NAME", "DESCRIPTION") VALUES (6, 'senior.tester', 'senior.tester.desc');
INSERT INTO "ROLE" ("ID", "ROLE_NAME", "DESCRIPTION") VALUES (7, 'tester', 'tester.desc');
INSERT INTO "ROLE" ("ID", "ROLE_NAME", "DESCRIPTION") VALUES (8, 'admin', 'admin.desc');
INSERT INTO "ROLE" ("ID", "ROLE_NAME", "DESCRIPTION") VALUES (9, 'leader', 'leader.desc');
INSERT INTO "ROLE" ("ID", "ROLE_NAME", "DESCRIPTION") VALUES (10, 'quality', 'quality.desc');
/*Add user rights*/
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (1, 'testplan.execute');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (2, 'testplan.create.build');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (3, 'testplan.metrics');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (4, 'testplan.planning');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (5, 'testplan.user_role.assigment');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (6, 'testcase.view');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (7, 'testcase.modify');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (8, 'requirement.view');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (9, 'requirement.modify');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (10, 'product.modify');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (11, 'manage.users');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (12, 'testplan.create');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (13, 'events.view');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (14, 'events.management');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (15, 'system.configuration');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (16, 'project.viewer');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (17, 'quality.assurance');
/*Set rights per role*/
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 1);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 2);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 3);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 4);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 5);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 6);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 7);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 8);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 9);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 10);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 11);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 12);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 13);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 14);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 15);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 16);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 17);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (5, 3);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (5, 6);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (4, 3);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (4, 6);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (4, 7);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (4, 8);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (4, 9);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (7, 1);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (7, 3);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (7, 6);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (6, 1);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (6, 2);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (6, 3);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (6, 6);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (6, 7);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (6, 9);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (9, 1);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (9, 2);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (9, 3);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (9, 4);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (9, 5);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (9, 6);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (9, 7);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (9, 8);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (9, 9);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (9, 12);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (10, 2);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (10, 5);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (10, 6);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (10, 8);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (10, 9);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (10, 12);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (10, 16);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (10, 17);
/*Add assignment types*/
INSERT INTO "ASSIGMENT_TYPE" ("ID", "FK_TABLE", "DESCRIPTION") VALUES (1, 'test_plan_has_test', 'testcase.execution');
INSERT INTO "ASSIGMENT_TYPE" ("ID", "FK_TABLE", "DESCRIPTION") VALUES (2, 'test_case', 'testcase.review');
/*Add assignment statuses*/
INSERT INTO "ASSIGNMENT_STATUS" ("ID", "NAME", "DESCRIPTION") VALUES (1, 'assignment.status.open', 'assignment.status.open.desc');
INSERT INTO "ASSIGNMENT_STATUS" ("ID", "NAME", "DESCRIPTION") VALUES (2, 'assignment.status.closed', 'assignment.status.closed.desc');
INSERT INTO "ASSIGNMENT_STATUS" ("ID", "NAME", "DESCRIPTION") VALUES (3, 'assignment.status.completed', 'assignment.status.completed.desc');
INSERT INTO "ASSIGNMENT_STATUS" ("ID", "NAME", "DESCRIPTION") VALUES (4, 'assignment.status..todo.urgent', 'assignment.status.todo.urgent.desc');
INSERT INTO "ASSIGNMENT_STATUS" ("ID", "NAME", "DESCRIPTION") VALUES (5, 'assignment.status.todo', 'assignment.status.todo.desc');
/*Add requirement types*/
INSERT INTO "REQUIREMENT_TYPE" ("ID", "NAME", "DESCRIPTION", "LEVEL") VALUES (1, 'UN', 'User Need', 0);
INSERT INTO "REQUIREMENT_TYPE" ("ID", "NAME", "DESCRIPTION", "LEVEL") VALUES (2, 'PS', 'Product Specification', 1);
INSERT INTO "REQUIREMENT_TYPE" ("ID", "NAME", "DESCRIPTION", "LEVEL") VALUES (3, 'SA', 'System Architecture', 2);
INSERT INTO "REQUIREMENT_TYPE" ("ID", "NAME", "DESCRIPTION", "LEVEL") VALUES (4, 'HW', 'Hardware', 3);
INSERT INTO "REQUIREMENT_TYPE" ("ID", "NAME", "DESCRIPTION", "LEVEL") VALUES (5, 'SW', 'Software', 3);
INSERT INTO "REQUIREMENT_TYPE" ("ID", "NAME", "DESCRIPTION", "LEVEL") VALUES (6, 'Labeling', 'Labeling requirements', 1);
INSERT INTO "REQUIREMENT_TYPE" ("ID", "NAME", "DESCRIPTION", "LEVEL") VALUES (7, 'Standards', 'Related to applicable standards', 1);

/*Add requirement statuses*/
INSERT INTO "REQUIREMENT_STATUS" ("ID", "STATUS") VALUES (1, 'general.open');
INSERT INTO "REQUIREMENT_STATUS" ("ID", "STATUS") VALUES (2, 'general.approved');
INSERT INTO "REQUIREMENT_STATUS" ("ID", "STATUS") VALUES (3, 'general.obsolete');
INSERT INTO "REQUIREMENT_STATUS" ("ID", "STATUS") VALUES (4, 'general.rejected');
/*Add Spec levels*/
INSERT INTO "SPEC_LEVEL" ("ID", "NAME", "DESCRIPTION") VALUES (1, 'spec.level.user.need', 'spec.level.user.need.desc');
INSERT INTO "SPEC_LEVEL" ("ID", "NAME", "DESCRIPTION") VALUES (2, 'spec.level.requirement', 'spec.level.requirement.desc');
INSERT INTO "SPEC_LEVEL" ("ID", "NAME", "DESCRIPTION") VALUES (3, 'spec.level.system', 'spec.level.system.desc');
INSERT INTO "SPEC_LEVEL" ("ID", "NAME", "DESCRIPTION") VALUES (4, 'spec.level.arch', 'spec.level.arch.desc');
INSERT INTO "SPEC_LEVEL" ("ID", "NAME", "DESCRIPTION") VALUES (5, 'spec.level.module', 'spec.level.module.desc');
/*Add settings*/
INSERT INTO "VM_SETTING" ("ID", "SETTING", "BOOL_VAL", "INT_VAL", "LONG_VAL", "STRING_VAL") VALUES (1, 'version.high', 0, 0, '0', NULL);
INSERT INTO "VM_SETTING" ("ID", "SETTING", "BOOL_VAL", "INT_VAL", "LONG_VAL", "STRING_VAL") VALUES (2, 'version.mid', 0, 0, '0', NULL);
INSERT INTO "VM_SETTING" ("ID", "SETTING", "BOOL_VAL", "INT_VAL", "LONG_VAL", "STRING_VAL") VALUES (3, 'version.low', 0, 1, '0', NULL);
INSERT INTO "VM_SETTING" ("ID", "SETTING", "BOOL_VAL", "INT_VAL", "LONG_VAL", "STRING_VAL") VALUES (4, 'password.aging', 0, 90, '0', NULL);
INSERT INTO "VM_SETTING" ("ID", "SETTING", "BOOL_VAL", "INT_VAL", "LONG_VAL", "STRING_VAL") VALUES (5, 'password.attempts', 0, 3, '0', NULL);
INSERT INTO "VM_SETTING" ("ID", "SETTING", "BOOL_VAL", "INT_VAL", "LONG_VAL", "STRING_VAL") VALUES (6, 'password.unusable_period', 0, 365, '0', NULL);
INSERT INTO "VM_SETTING" ("ID", "SETTING", "BOOL_VAL", "INT_VAL", "LONG_VAL", "STRING_VAL") VALUES (7, 'version.postfix', 0, 0, '0', 'Alpha');
/*Add Admin user*/
INSERT INTO "VM_USER" ("ID", "USERNAME", "PASSWORD", "EMAIL", "FIRST_NAME", "LAST_NAME", "LOCALE", "USER_STATUS_ID") VALUES (1, 'admin', '21232f297a57a5a743894a0e4a801fc3', '', 'System', 'Administrator', 'en', 1);
INSERT INTO "USER_HAS_ROLE" ("USER_ID", "ROLE_ID") VALUES (1, 8);