/*Default Workflows*/
/*Approval*/
INSERT INTO "WORKFLOW" ("ID", "WORKFLOW_NAME") VALUES (1, 'worflow.approval');

INSERT INTO "WORKFLOW_STEP" ("ID", "WORKFLOW", "STEP_NAME") VALUES (1, 1, 'general.start');
INSERT INTO "WORKFLOW_STEP" ("ID", "WORKFLOW", "STEP_NAME") VALUES (2, 1, 'general.approved');
INSERT INTO "WORKFLOW_STEP" ("ID", "WORKFLOW", "STEP_NAME") VALUES (3, 1, 'general.rejected');

INSERT INTO "STEP_TRANSITIONS_TO_STEP" ("SOURCE_STEP", "SOURCE_STEP_WORKFLOW", "TARGET_STEP", "TARGET_STEP_WORKFLOW", "TRANSITION_NAME") VALUES (1, 1, 2, 1, 'general.approve');
INSERT INTO "STEP_TRANSITIONS_TO_STEP" ("SOURCE_STEP", "SOURCE_STEP_WORKFLOW", "TARGET_STEP", "TARGET_STEP_WORKFLOW", "TRANSITION_NAME") VALUES (1, 1, 3, 1, 'general.reject');
