/*Risk Management Roles*/
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (18, 'risk.management.editor');
INSERT INTO "USER_RIGHT" ("ID", "DESCRIPTION") VALUES (19, 'risk.management.view');

/*Assign to roles*/
/*Admin*/
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 18);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (8, 19);
/*Quality*/
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (10, 18);
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (10, 19);
/*Test Designer*/
INSERT INTO "ROLE_HAS_RIGHT" ("ROLE_ID", "RIGHT_ID") VALUES (4, 19);