/*
 * Copyright 2026 Javier A. Ortiz Bultron javier.ortiz.78@gmail.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.validation.manager.core.db;

import java.io.IOException;
import java.io.Writer;
import org.eclipse.persistence.exceptions.ValidationException;
import org.eclipse.persistence.platform.database.H2Platform;

/**
 * EclipseLink's stock H2Platform emits the H2 1.x-only "{@code INTEGER IDENTITY}"
 * column clause, which H2 2.x rejects (it requires
 * {@code GENERATED BY DEFAULT AS IDENTITY}). This bug is still present in
 * EclipseLink 5.x, so this override stays until the upstream platform is fixed.
 */
public class H2PlatformV2 extends H2Platform {

    private static final long serialVersionUID = 1L;

    @Override
    public void printFieldIdentityClause(Writer writer) throws ValidationException {
        try {
            writer.append(" GENERATED BY DEFAULT AS IDENTITY");
        } catch (IOException e) {
            throw ValidationException.logIOError(e);
        }
    }

    /**
     * H2 2.x removed the "{@code CALL IDENTITY()}" statement EclipseLink uses to
     * fetch the last identity value. Declaring generated-key support makes
     * EclipseLink read the ID back through JDBC {@code getGeneratedKeys()}
     * instead of falling back to that statement.
     */
    @Override
    public boolean supportsReturnGeneratedKeys() {
        return true;
    }
}
